### ISSUE TITLE
TRPC + NextJS example

### ISSUE THREAD

**Issue by garrettg123** [klis87/normy#5]
Hi there, love what you've built here! I'm wondering if there's a way to use this with NextJS.

Thanks

**Comment by klis87** [comment]
Hi, I am glad you like it!

There should be no issue at all, because normalization is unnecessary on server side. So you can use it with trpc and react-query like without ssr at all.

It probably should be added to docs, but now I am thinking that here - https://github.com/klis87/normy/tree/master/packages/normy-react-query#disabling-of-normalization-per-query-and-mutation-arrow_up

you could do sth like:
```tsx
<QueryNormalizerProvider
  queryClient={queryClient}
  normalizerConfig={{ normalize: typeof window !== 'undefined' }}
>
  {children}
</QueryNormalizerProvider>
```

which will turn off normalization on the server.

**Comment by klis87** [comment]
For debugging I recommend https://github.com/klis87/normy#debugging-arrow_up

I will check infinite scrolling and add it to examples to check if there are any problems with it.

**Comment by klis87** [comment]
I am not sure I understand what you mean. 

> Is there any way to short-circuit a request like in Apollo GraphQL

For example I do not understand this part, as even if you have `taskResult` fetched, it cannot prevent list from fetching, as list can and probably does contain more items than already fetched one

> The task already exists. I just don't want my component using the task to update if the entire list updates, only if that single task updates.

Queries are unrelated to each other, `normy` only normalizes data for each query, but it does not update other queries

Only muutation data is checked and relevant dependent queries which contain objects from mutation ID are updated. Anyway, thx to react-query structural sharing, if query data is the same after the update, `useQuery` will contain the same `data` reference.

-------------

If your question is about something else, please let me know and I will try to answer.

**Comment by klis87** [comment]
Could you please raise a separate issue? Then people with similar problem could benefit from answers, thanks!
